### ISSUE TITLE
Review and incorporate peer review feedback

### ISSUE THREAD

**Issue by ethanielp** [annabelle-ep/dsci-310-group-04#54]

**Comment by oliviacyp** [comment]
- [x] I would prefer to see the generated reports and references.bib to be inside a folder
- [x] It would be a better idea to include the instruction on using make command to reproduce the documents
- [x] There is a hard coding part in creating histogram plots for each category (Note: I saw your note but I hope you can figure out how to fix it)
- [x] Don't forget to include the names of the authors in your report.
- [x] As someone who does not know what the trainer does, what do the numbers mean? For instance, does a large train_n mean something good, or does a small train_n mean something good. Or even easier, for dancibility, key, speechiness, etc, does a higher value mean more presence of the category or less.
- [x] The genre classifier files would probably be suited better if they were renamed so that there is a unique identifier that is not just the file type.
- [x] One way in which to fix some of the problems in graphs is to insert the graphs as images and leaving a note that the graph might look different per machine, rather than having it as an incorrectly loaded graph.
- [x] I really like how your README file is organized, especially About section where you mention the predictor variables, the model you used and the accuracy you get for that model before moving onto the Usage/Replication.
- [x] I think you should try to be more clear when naming your functions. For example, the tests/testthat folder implies that these are your test functions, but when you go into the folder and check the files, there are also helper functions (helper-classy_read.R, helper-count_proportion.r and helper-create_faceted_hist_plot.R) along with test functions. I think you should create a different folder for helper functions and use them as appropriate.
- [x] I think you should add the instructions for make. Some questions that you could answer in Usage or Replication: How to use make? What files and folders make will create? Where are they specifically located? Also, mention that make all takes round x minutes, and you have the rstudio docker command in your Makefile and running make rstudio runs the docker container. And maybe clarify you don't run the rstudio docker container when you run make all.
- [x] Figure 1: Histograms of each of the features that we are using, differentiated by labeled genre in your genre_classifier_project.Rmd file has so many different small distribution visualizations, and the numbers are all collided, so it is hard to understand anything from the figure. So, I would suggest you to try to update that.
- [x] I like how you have clean in your Makefile, and you also make the directory Outputs in your Makefile.
Another suggestion I have is creating different folders within your Outputs folder such as data and figures folders, so that you can save the inital csv files such as 1.1-spotify_songs.csv and 2.1-tidy_song_data.csv. Since you have a lot of figures and files, this might be a good idea.
- [x] Also make sure to have the authors in the actual report.

GENERAL
- [x] **Example usage:** Do the authors include examples of how to use the software to reproduce the data analysis?
- [x] **Community guidelines:** Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support
- [x] **Authors:** Does the report include a list of authors with their affiliations?
- [x] **Style guidelides:** Does the code adhere to well known language style guides?
- [x] **Tests:** Are there automated tests or manual steps described so that the function of the software can be verified? Are they of sufficient quality to ensure software robsutness?
- [x] **Automation:** Can someone other than the authors easily reproduce the entire data analysis?
